[package]
name = "xesite"
version = "2.0.0"
authors = ["Christine Dodrill <me@christine.website>"]
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
atom_syndication = { version = "0.9", features = ["with-serde"] }
chrono = "0.4"
comrak = "0.8"
envy = "0.4"
glob = "0.3"
hyper = "0.13"
lazy_static = "1.4"
log = "0"
mime = "0.3.0"
pretty_env_logger = "0"
prometheus = { version = "0.9", default-features = false, features = ["process"] }
rand = "0"
rss = "1"
ructe = "0.11"
serde_dhall = "0.5.3"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
sitemap = "0.4"
thiserror = "1"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
xml-rs = "0.8"

# workspace dependencies
go_vanity = { path = "./lib/go_vanity" }
jsonfeed = { path = "./lib/jsonfeed" }

[build-dependencies]
ructe = { version = "0.11", features = ["warp02"] }

[workspace]
members = [
  "./lib/go_vanity",
  "./lib/jsonfeed"
]
