name: Dependabot super yolo

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  run-custom-command:
    if: ${{ github.actor_id == '49699333' }} # Dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          submodules: true
      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --auto ${{ github.event.number }}
        env:
          GH_TOKEN: ${{ github.token }}
